NAME = libft.a

SRC =			ft_memset.c				
			ft_bzero.c				
			ft_memcpy.c				
			ft_memccpy.c			
			ft_memmove.c		
			ft_memchr.c				
			ft_memcmp.c			
			ft_strlen.c				
			ft_strdup.c			
			ft_strndup.c			
			ft_strcpy.c				
			ft_strncpy.c			
			ft_strcat.c				
			ft_strncat.c			
			ft_strlcat.c		
			ft_strchr.c				
			ft_strrchr.c		
			ft_strstr.c				
			ft_strnstr.c			
			ft_strcmp.c			
			ft_strncmp.c			
			ft_atoi.c				
			ft_atof.c	
			ft_toupper.c	
			ft_tolower.c		
			ft_memdel.c			
			ft_strnew.c		
			ft_strdel.c		
			ft_strclr.c			
			ft_striter.c	
			ft_striteri.c		
			ft_strequ.c		
			ft_strnequ.c
			ft_strsub.c			
			ft_strmap.c			
			ft_strmapi.c		
			ft_itoa.c		
			ft_strsplit.c	
			ft_strsplit_esc.c	
			ft_strsplit_mult.c	
			ft_strjoin.c		
			ft_strtrim.c		
			ft_strtrim_carac.c	
			ft_putchar.c		
			ft_putstr.c			
			ft_putnbr.c		
			ft_putnbrf.c		
			ft_puttab.c		
			ft_free_tab.c		
			ft_dlist_create.c	
			ft_dlist_del.c		
			ft_dlist_fct.c		
			ft_dlist_fct2.c	
			get_next_line.c		
			ft_trigo.c			
			ft_math.c


OBJECTS	= $(SRC:.c=.o)

all: $(NAME)

$(NAME):
	gccw -c $(SRC)
	ar rc $(NAME) $(OBJECTS)
	ranlib $(NAME)
	@echo "Built library."


clean:
	rm -rf $(OBJECTS)
	@echo "cleaned up object files."	
	
fclean: clean
	rm -rf $(NAME)
	@echo "cleaned up compiled files."

re: fclean all

.PHONY: all re fclean clean